### ISSUE TITLE
Installer trying to access an unprovided partition

### ISSUE THREAD

**Issue by BobbedBob** [Vanilla-OS/Albius#44] opened 2024-01-18 01:34 UTC
![20240117_203739](https://github.com/Vanilla-OS/vanilla-installer/assets/73052469/2654c1c8-d50c-4bf9-8ef6-a1055521c543)
I asked the installer to install with the partitions 6/7/8/9, yet it's trying to access p5 which was on lvm2 (photo says it's fat32).
I followed this blog post when [partitioning ](https://vanillaos.org/blog/article/2023-11-22/vanilla-os-orchid---devlog-22-nov#new-partitioning-structure)the disk.

**Comment by taukakao** [comment] 2024-02-03 02:02
Could you test if this is fixed in the latest iso?
https://github.com/Vanilla-OS/live-iso/actions/runs/7763576067

! Keep in mind that it's still dangerous. So don't do it if you have important data on the disk.  !


@BobbedBob  @ericwikman

**Comment by ericwikman** [comment] 2024-02-03 04:18
This did seem to fix it!

I'm glad you were able to reproduce and fix it. I too am able to reproduce the (hopefully former) issue reliably now. I am curious how you fixed it, and if I can see the commit for my own education.

I was able to determine that it did destroy the MyASUS WinRE recovery partition (no big deal, I knew this was a beta). I decided to just let VOS wipe my drive completely clean and do the full drive install, which worked fine. 

Once the drive was wiped it gave me the opportunity to try many different ways to reproduce the issue. The method to reproduce I used was to delete all partitions, then create a 10gb partition at the start of the drive and a 10gb partition at the end of the drive. Then I created the 4 partitions for VOS directly after the first partition, so the ordered ends up being 1 3 4 5 6 2. It destroys partition 2 and the install fails. 

If there is a partition at the end of the drive before you create the VOS partitions it won't work. I suspect if I was to create 3 partitions on a blank drive and then delete the 2nd partition and then create the 4 VOS partitions it would end up something like 1 3 2 4 5 6 (if there isn't enough space between 3 and 2 to fit 4/5/6) that it would fail as well, but did not try it. Or if I was to manually set the sectors for each partition in a funky order. 

It does not seem to matter how many partitions are before or after the VOS ones as long as they are all in sector order (1 2 3 4 5 6 7 8, where 3-6 are VOS), that installs fine. 

I probably did like a dozen install attempts today, so I've gotten pretty familiar with the process and have a few items of feedback (if this is an acceptable place for now). 

1) I found that I had to reboot after using GParted to create the 4 VOS partitions. If I did not, then the install would fail, but not always in the same manner. This is a screenshot of one failure, in step 2 it panic's because there is no /dev/sda6 (but GParted says there is (I did commit the changes to the partition table before continuing with the install)):

![Screenshot from 2024-02-03 00-48-09](https://github.com/Vanilla-OS/Albius/assets/455225/25c1cf5f-85ef-44ce-97db-9fb9212054c2)

2) this may be more of a GParted issue, but sometimes I could deactivate the vos-root partition to allow me to be able to delete it, and sometimes I could not. When deactivating did not work, then I could run lvremove from the command line to release the lock on the partition so that I could delete it from GParted

3) also probably a GParted issue, but if I deleted the 4 partitions, reboot, and then add them back in the exact same order and same size, the deleted partitions returned to their former state. The vos-root I create as unformatted, but after I commit the changes it magically becomes lvm2. Even if I first told GParted to format the partition to be ext2, then commit, reboot, delete the partition, commit, reboot, create the partition. If it has the same start and end sector, it goes back to its old state.

4) The laptop is not connected via Ethernet, I'm only using wifi. If I connect to wifi from the installer, then the installer crashes eventually, typically before I click on the final button to begin the install (although once I was able to get it actually installing before it crashed). If I connect to wifi from GNOME before I begin the install process then it does not crash. This is also true on the Vanilla OS First Setup program after the install when it opens the first boot walk-through (true both ways, if I setup wifi from the First Setup program then it eventually crashes, but if I do it from Gnome it does not). No error message displays, it just disappears.

5) In the installer on the Configure Disk page it says that you don't need a Swap partition for hibernation, but your Nov 22 Devlog blog post (with the partition instructions) says you do. I know the documentation is not up to date yet, but that blog post is linked from the beta announcement blog post.

6) It would be nice on the language and the keyboard selection pages if it told you at the top which choice has been selected without having to scroll through everything to see it is English US. 

7) It would be nice if the settings you make in the installer persist to the First Setup wizard. That is for language, keyboard, timezone, and wifi password.

None of the above are important to me, feel free to ignore. I'm happy you got the issue resolved.

**Comment by taukakao** [comment] 2024-02-03 05:13
Thanks for testing it.

The issue was in an assumption that an array would have partitions sda1, sda2 and so on in order. 
Since this is not always the case, it would select for example the second partiton of your disk because you selected sda2, no matter if that was actually correct.
This is the commit that fixed it:
https://github.com/Vanilla-OS/Albius/commit/75ca3dca0eb7262f98710c20719a8103657e522d

**Comment by taukakao** [comment] 2024-02-03 05:14
And no, an issue is always only suitable for one topic, so if you care about the other issues, please open new issues for them. (Except for 2 and 3, since they are gparted issues)

**Closed** 2024-02-03 05:15 UTC
Labels: bug
